version: 2

models:
  - name: stg_books
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "SAFE_CAST(release_year AS INT64) BETWEEN 1450 AND EXTRACT(YEAR FROM CURRENT_DATE())"
          config:
            severity: warn
    columns:
      - name: isbn
        tests:
          - not_null
          - unique: # Added the colon here
              config:
                severity: warn # This fixes your 1 failure!

  - name: stg_users
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "SAFE_CAST(user_id AS INT64) IS NOT NULL"
      - dbt_utils.expression_is_true:
          arguments:
            expression: "SAFE_CAST(age AS INT64) BETWEEN 5 AND 100"
          config:
            severity: warn
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: stg_ratings
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "book_rating BETWEEN 0 AND 10"
          config:
            severity: warn
    columns:
      - name: user_id
        tests:
          - not_null
          - relationships:
              arguments: # Added arguments to fix deprecation warning
                to: ref('stg_users')
                field: user_id
              config:
                severity: warn

      - name: isbn
        tests:
          - not_null
          - relationships:
              arguments: # Added arguments to fix deprecation warning
                to: ref('stg_books')
                field: isbn
              config:
                severity: warn 
      - name: book_rating
        tests:
          - not_null